//! Valence side effect: `UserCounter` mutation → Boson leaderboard task.
//!
//! Implements `SideEffect` for `UserCounter`. On create/update (not delete,
//! not reset-to-zero), reads old/new scores from the mutation and enqueues
//! [`crate::scripts::check_leaderboard_changes`] via
//! `CheckLeaderboardChanges::send_with(actor_json, params)`.

use async_trait::async_trait;
use valence::{extract_id_from_record, Mutation, MutationKind, SideEffect};

use crate::generated::UserCounter;

/// Side effect on `UserCounter` that enqueues leaderboard rank-diff work.
///
/// Platform bridge: Valence mutation metadata → Boson `send_with`.
///
/// Skips deletes and value-to-zero writes (daily reset) to avoid notification
/// storms. Actor JSON is serialized from `mutation.valence().actor()` so the
/// Boson task rebuilds Valence with the same actor via
/// `boson_valence_identity::valence_from_context`.
///
/// # Examples
///
/// Enqueue shape used inside `on_mutation` (macros generate the typed sender;
/// schema lists `side_effects: [LeaderboardNotifier]`):
///
/// ```rust,ignore
/// use counter_app_worker::scripts::check_leaderboard_changes::{
///     CheckLeaderboardChanges, CheckLeaderboardChangesParams,
/// };
///
/// CheckLeaderboardChanges::send_with(
///     actor_json,
///     CheckLeaderboardChangesParams {
///         user_id: "alice".into(),
///         old_value: 3,
///         new_value: 4,
///     },
/// )
/// .await?;
/// ```
pub struct LeaderboardNotifier;

/// Whether [`LeaderboardNotifier`] should enqueue a leaderboard check.
///
/// Returns `false` for deletes, daily reset-to-zero writes, and no-op score
/// updates. Exposed so contract tests can lock the skip policy without a full
/// Valence mutation harness.
#[must_use]
pub fn should_enqueue_leaderboard_check(
    is_delete: bool,
    new_score: Option<i64>,
    old_score: i64,
    new_score_field: i64,
) -> bool {
    if is_delete {
        return false;
    }
    // Daily reset (and any write that lands on zero) must not fan out notifies.
    if new_score == Some(0) || new_score_field == 0 {
        return false;
    }
    if old_score == new_score_field {
        return false;
    }
    true
}

#[async_trait]
impl SideEffect<UserCounter> for LeaderboardNotifier {
    async fn on_mutation(&self, mutation: &Mutation<'_, UserCounter>) -> valence::Result<()> {
        let is_delete = matches!(mutation.kind(), MutationKind::Delete);
        let after_score = mutation.after().map(|after| *after.value());

        // Extract the user_id from the mutated record (needed after the skip gate).
        let after = mutation.after().ok_or_else(|| {
            valence::Error::Internal(
                "[counter-app-worker] LeaderboardNotifier: missing after record".into(),
            )
        })?;

        let user_id = extract_id_from_record(after.user()).unwrap_or_default();

        // Read old/new values from the field changes.
        let changes = mutation.fields();
        let old_value = changes.value.before().copied().unwrap_or(0);
        let new_value = changes.value.after().copied().unwrap_or(0);

        if !should_enqueue_leaderboard_check(is_delete, after_score, old_value, new_value) {
            return Ok(());
        }

        log::info!(
            "[counter-app-worker] LeaderboardNotifier: score {old_value} -> {new_value}, enqueuing leaderboard check"
        );

        let actor_json = serde_json::to_value(mutation.valence().actor())?;

        // Boson: typed task sender generated by `#[boson_macros::task]`.
        // `send_with(actor_json, params)` enqueues work; the worker rebuilds Valence
        // via `boson_valence_identity::valence_from_context` inside the task.
        crate::scripts::check_leaderboard_changes::CheckLeaderboardChanges::send_with(
            actor_json,
            crate::scripts::check_leaderboard_changes::CheckLeaderboardChangesParams {
                user_id,
                old_value,
                new_value,
            },
        )
        .await
        .map_err(|e| valence::Error::Internal(e.to_string()))?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::should_enqueue_leaderboard_check;

    #[test]
    fn enqueue_on_score_increase_happy() {
        assert!(should_enqueue_leaderboard_check(false, Some(10), 5, 10));
    }

    #[test]
    fn skip_delete_sad() {
        assert!(!should_enqueue_leaderboard_check(true, Some(10), 5, 10));
    }

    #[test]
    fn skip_reset_to_zero_sad() {
        // Daily reset path: after-record value is 0.
        assert!(!should_enqueue_leaderboard_check(false, Some(0), 40, 0));
        assert!(!should_enqueue_leaderboard_check(false, Some(0), 40, 40));
    }

    #[test]
    fn skip_noop_score_sad() {
        assert!(!should_enqueue_leaderboard_check(false, Some(7), 7, 7));
    }
}
